# Generated by Django 4.2.9 on 2024-02-04 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_reviewdessert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to=settings.AUTH_USER_MODEL),
        ),
    ]
