# Generated by Django 4.2.9 on 2024-02-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_reviewdessert_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewdessert',
            name='user',
        ),
    ]
