# Generated by Django 4.2.9 on 2024-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_reviewdessert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
