# Generated by Django 4.2.9 on 2024-02-06 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_remove_dessert_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdessert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_dessert', to=settings.AUTH_USER_MODEL),
        ),
    ]
