# Generated by Django 4.2.9 on 2024-02-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_dessert_user_alter_reviewdessert_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdessert',
            name='review_desserts',
        ),
        migrations.AddField(
            model_name='reviewdessert',
            name='posts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='post.dessert'),
            preserve_default=False,
        ),
    ]
