# Generated by Django 4.2.9 on 2024-02-09 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_remove_reviewdessert_review_desserts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_d', to=settings.AUTH_USER_MODEL),
        ),
    ]
