# Generated by Django 4.2.9 on 2024-02-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_dessert_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdessert',
            old_name='posts',
            new_name='post',
        ),
    ]
